config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/users#index'
  namespace :admin do
   resources :users
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
    user ||= User.new # guest user (not logged in)
      if user.role.name == "admin"
        can :manage, :all
      elsif user.role.name == "user"
        cannot :manage, :all
      end
  
  
  end
end

app/models/designation.rb
class Designation < ActiveRecord::Base
	has_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many:users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	belongs_to :designation
  belongs_to :role
	validates :email,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :login,uniqueness: true
	#validates :password, confirmation: true,length: 6..20
   validates :work_phone,format: { with: /\A(180[-]?)?\d{3}[-]?\d{3}[-]?\d{4}\z/}
    #validate :join_date_check_with_dob
end

  def join_date_check_with_dob
    errors.add(:date_of_joining, "should always be greater than your Date of birth") if
      !date_of_joining.blank? and date_of_joining < date_of_birth
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource except: [:create]
	def index
		@user=User.all
	end

  def new 
    @user = User.new
    @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
    @role_array=Role.all.map{|d|[d.name,d.id]}
  end

	def show
		@user=User.find(params[:id])
	end

  def edit
    @user = User.find(params[:id])
    @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
    @role_array=Role.all.map{|d|[d.name,d.id]}
  end

	def create
	  @user=User.new(user_params)
		# @user.fname = params[:fname]
		if @user.is_active==true then @user.is_locked=false else @user.is_locked=true end
        if @user.save
	        redirect_to [:admin,@user]
	      else
         @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
         @role_array=Role.all.map{|d|[d.name,d.id]}
         render :new
        end
	 end

  def update
    @user = User.find(params[:id])
    @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
    @role_array=Role.all.map{|d|[d.name,d.id]}
    if @user.update(user_params)
      redirect_to [:admin,@user]
    else
      @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
      @role_array=Role.all.map{|d|[d.name,d.id]}
      render 'edit'
    end
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :middle_name,:last_name,:email,:login,:password,:password_confirmation,:employee_id,:date_of_birth,:gender,:time_zone,:designation_id,:date_of_joining,:is_locked,:is_active,:education,:comments,:date_of_deactivation,:reason_for_deactivation,:work_phone,:role_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access Denied"
    redirect_to user_url(:id => current_user.id)
 end

def update_sanitized_params
  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :middle_name,:last_name,:email,:login,:password,:password_confirmation,:employee_id,:date_of_birth,:gender,:time_zone,:designation_id,:date_of_joining,:is_locked,:is_active,:education,:comments,:date_of_deactivation,:reason_for_deactivation,:work_phone)}
end
#before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#load_and_authorize_resource
	def index
	end
	def show
		@user=User.find(params[:id])
	end

	def create
		@user=User.new(params.require(:user).permit(:first_name, :middle_name,:last_name,:email,:login,:password,:password_confirmation,:employee_id,:date_of_birth,:gender,:time_zone,:designation_id,:date_of_joining,:is_locked,:is_active,:education,:comments,:date_of_deactivation,:reason_for_deactivation,:work_phone))
		# @user.fname = params[:fname]
		byebug
		if @user.is_active==true then @user.is_locked=false else @user.is_locked=true end
        if @user.save
	        redirect_to user_path(@user)
	    else
            render new_user_path
        end
	end

	def new 
        @designation_array=Designation.all.map{|d|[d.designation_name,d.id]}
		@user = User.new
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/edit.html.erb
<h1 align="center">User Registration</h1>
<% if @user.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@user.errors.count, "error") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for [:admin,@user] do |f| %>
  <div class="row">
  <div class="col-md-4">
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name,class:"form-control",:required => true %>
    </div>
  </div>
  <div class="col-md-4">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name,class:"form-control" %>
  </div>
  <div class="col-md-4">
    <%= f.label :last_name  %>
    <%= f.text_field :last_name,class:"form-control",:required => true %>
  </div>
  </div>
  <div class="row">
  <div class="col-md-6">
    <%= f.label :email %>
    <%= f.text_field :email,class:"form-control",:required => true %>
    </div>
    <div class="col-md-6">
    <%= f.label :login %>
    <%= f.text_field :login,class:"form-control",:required => true %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :employee_id %>
    <%= f.text_field :employee_id,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_birth,'Date of birth' %>
    <div class="form control">
    <%= f.date_select :date_of_birth, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :gender %>
    <div class="form control">
  <%= f.select(:gender, options_for_select([['Male'], ['Female']])) %>
  </div>
  </div>
   </div>
   <div class="row">
   <div class="col-md-4">
   <%= f.label :time_zone %>
   <div class="form control">
   <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones,default: "Pacific Time (US & Canada)") %>
   </div>
   </div>
   <div class="col-md-4">
  <%= f.label :designation_id %>
  <div class="form control">
  <%= f.select(:designation_id, options_for_select(@designation_array))%>
  </div>
  </div>
  <div class="col-md-4">
    <%= f.label :date_of_joining,'Date of joining' %>
    <div class="form control">
    <%= f.date_select(:date_of_joining, order: [:day, :month, :year],start_year: 2000) %>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :work_phone %>
    <%= f.text_field :work_phone,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :education %>
    <%= f.text_area :education,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :comments %>
    <%= f.text_area :comments,class:"form-control" %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-1">
    <%= f.label :is_active,"Is Active" %>
    <%= f.radio_button(:is_active,true) %>
    </div>
    <div class="col-md-1">
    <%= f.label :is_active,"Is locked" %>
    <%= f.radio_button(:is_active,false) %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_deactivation,'Date of deactivation' %>
    <%# text_field_tag :date_of_deactivation , "data-provide"=>'datepicker',class:"form-control" %>
    <div class="form control">
    <%= f.date_select :date_of_deactivation, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :reason_for_deactivation,'Reason for deactivation' %>
    <div class="form control">
    <%= f.select(:reason_for_deactivation, options_for_select([['No longer an employee with us'],['Absconding'],['Long Medical Live']]),class:"form-control") %>
    </div>
    </div>
    <div class="col-md-2">
    <%= f.label :role_id %>
    <div class="form control">
  <%= f.select(:role_id, options_for_select(@role_array)) %>
  </div>
    </div>
    </div>
    </br>
    <div align="center">
    <%= f.submit class:"btn-primary"%>
    </div>
    <!--<div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>-->
<% end %>

app/views/admin/users/index.html.erb
<nav class="navbar navbar-default">
<div class="container">
 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">EBO</a>
    </div>
<div>
<ul class="nav navbar-nav">
  <li role="presentation" class="active"><%= link_to 'Register new users', new_admin_user_path %></li>
  </ul>
  </div>
</div>
</nav>

<h1>Users</h1>

</br>
<div align="center">
<table class="table table-striped">
  <tr>
    <th>Users</th>
    <th colspan="4"></th>
  </tr>
 <%if @user!=nil %>
  <% @user.each do |user| %>
    <tr>
      <td><%= user.first_name%></td>
      <td><%= link_to 'Show', admin_user_path(user) %></td>
      <% if can? :update , @user%>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <% end %>
      <% if can? :destroy , @user%>
      <td><%= link_to 'Destroy', admin_user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  <% end %>
</table>
</div>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/admin/users/login.html.erb
<%=label_tag :login %>
<%=text_field_tag :login,class:"form-control",:required => true %>
<%=label_tag :password %>
<%=password_field_tag :password,class:"form-control",:required => true %>
<%=submit_tag class:"btn-primary"%>

app/views/admin/users/new.html.erb
    <h1 align="center">User Registration</h1>
<% if @user.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@user.errors.count, "error") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user do |f| %>
  <div class="row">
  <div class="col-md-4">
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name,class:"form-control",:required => true %>
    </div>
  </div>
  <div class="col-md-4">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name,class:"form-control" %>
  </div>
  <div class="col-md-4">
    <%= f.label :last_name  %>
    <%= f.text_field :last_name,class:"form-control",:required => true %>
  </div>
  </div>
  <div class="row">
  <div class="col-md-6">
    <%= f.label :email %>
    <%= f.text_field :email,class:"form-control",:required => true %>
    </div>
    <div class="col-md-6">
    <%= f.label :login %>
    <%= f.text_field :login,class:"form-control",:required => true %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-6">
    <%= f.label :password %>
    <%= f.password_field :password,class:"form-control",:required => true %>
    </div>
    <div class="col-md-6">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,class:"form-control",:required => true %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :employee_id %>
    <%= f.text_field :employee_id,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_birth,'Date of birth' %>
    <div class="form control">
    <%= f.date_select :date_of_birth, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :gender %>
    <div class="form control">
  <%= f.select(:gender, options_for_select([['Male'], ['Female']])) %>
  </div>
  </div>
   </div>
   <div class="row">
   <div class="col-md-4">
   <%= f.label :time_zone %>
   <div class="form control">
   <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones,default: "Pacific Time (US & Canada)") %>
   </div>
   </div>
   <div class="col-md-4">
  <%= f.label :designation_id %>
  <div class="form control">
  <%= f.select(:designation_id, options_for_select(@designation_array))%>
  </div>
  </div>
  <div class="col-md-4">
    <%= f.label :date_of_joining,'Date of joining' %>
    <div class="form control">
    <%= f.date_select(:date_of_joining, order: [:day, :month, :year],start_year: 2000) %>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :work_phone %>
    <%= f.text_field :work_phone,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :education %>
    <%= f.text_area :education,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :comments %>
    <%= f.text_area :comments,class:"form-control" %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-2">
    <%= f.label :is_active,"Is Active" %>
    <%= f.radio_button(:is_active,true) %>
    </div>
    <div class="col-md-2">
    <%= f.label :is_active,"Is locked" %>
    <%= f.radio_button(:is_active,false) %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_deactivation,'Date of deactivation' %>
    <%# text_field_tag :date_of_deactivation , "data-provide"=>'datepicker',class:"form-control" %>
    <div class="form control">
    <%= f.date_select :date_of_deactivation, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :reason_for_deactivation,'Reason for deactivation' %>
    <div class="form control">
    <%= f.select(:reason_for_deactivation, options_for_select([['No longer an employee with us'],['Absconding'],['Long Medical Live']]),class:"form-control") %>
    </div>
    </div>
    </div>
    </br>
    <div align="center">
    <%= f.submit class:"btn-primary"%>
    </div>
    <!--<div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>-->
<% end %>

app/views/admin/users/show.html.erb
<nav class="navbar navbar-default">
<div class="container">
 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">EBO</a>
    </div>
<div>
<ul class="nav navbar-nav">
  <li role="presentation" class="active"><%= link_to "Back to index page", admin_users_path %>
  </li>
  <li role="presentation" class="active"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  </ul>
  </div>
</div>
</nav>
<h3>Welcome <%= @user.first_name %></h3>
<table class="table table-striped">
<tr>
  <td><strong>First name:</strong></td>
  <td><%= @user.first_name %></td>
</tr>
<tr>
  <td><strong>Middle name:</strong></td>
  <td><%= @user.middle_name %></td>
</tr>
<tr>
  <td><strong>Last name:</strong></td>
  <td><%= @user.last_name %></td>
</tr>
<tr>
  <td><strong>Email:</strong></td>
  <td><%= @user.email %></td>
</tr>
<tr>
  <td><strong>Login:</strong></td>
  <td><%= @user.login %></td>
</tr>
<tr>
  <td><strong>Employee id </strong></td>
  <td><%= @user.employee_id %></td>
</tr>
<tr>
<td><strong>Date of birth </strong></td>
  <td><%= @user.date_of_birth %></td>
</tr>
<tr>
<td><strong>Gender </strong></td>
  <td><%= @user.gender %></td>
</tr>
<tr>
<td><strong>Time_zone </strong></td>
  <td><%= @user.time_zone %></td>
</tr>
<tr>
<td><strong>Gender </strong></td>
  <td><%= @user.gender %></td>
</tr>
<tr>
<td><strong>Date of joining </strong></td>
  <td><%= @user.date_of_joining %></td>
</tr>
<tr>
<td><strong>Designation id </strong></td>
  <td><%= @user.designation_id %></td>
</tr>
<td><strong>Education </strong></td>
  <td><%= @user.education %></td>
<tr>
<td><strong>Work phone </strong></td>
  <td><%= @user.work_phone %></td>
</tr>
<tr>
<td><strong>Role </strong></td>
  <td><%= @user.role.name%></td>
</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
hello world

app/views/users/login.html.erb
<%=label_tag :login %>
<%=text_field_tag :login,class:"form-control",:required => true %>
<%=label_tag :password %>
<%=password_field_tag :password,class:"form-control",:required => true %>
<%=submit_tag class:"btn-primary"%>

app/views/users/new.html.erb
    <h1 align="center">User Registration</h1>
<% if @user.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@user.errors.count, "error") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user do |f| %>
  <div class="row">
  <div class="col-md-4">
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name,class:"form-control",:required => true %>
    </div>
  </div>
  <div class="col-md-4">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name,class:"form-control" %>
  </div>
  <div class="col-md-4">
    <%= f.label :last_name  %>
    <%= f.text_field :last_name,class:"form-control",:required => true %>
  </div>
  </div>
  <div class="row">
  <div class="col-md-6">
    <%= f.label :email %>
    <%= f.text_field :email,class:"form-control",:required => true %>
    </div>
    <div class="col-md-6">
    <%= f.label :login %>
    <%= f.text_field :login,class:"form-control",:required => true %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-6">
    <%= f.label :password %>
    <%= f.password_field :password,class:"form-control",:required => true %>
    </div>
    <div class="col-md-6">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,class:"form-control",:required => true %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :employee_id %>
    <%= f.text_field :employee_id,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_birth,'Date of birth' %>
    <div class="form control">
    <%= f.date_select :date_of_birth, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :gender %>
    <div class="form control">
  <%= f.select(:gender, options_for_select([['Male'], ['Female']])) %>
  </div>
  </div>
   </div>
   <div class="row">
   <div class="col-md-4">
   <%= f.label :time_zone %>
   <div class="form control">
   <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones,default: "Pacific Time (US & Canada)") %>
   </div>
   </div>
   <div class="col-md-4">
  <%= f.label :designation_id %>
  <div class="form control">
  <%= f.select(:designation_id, options_for_select(@designation_array))%>
  </div>
  </div>
  <div class="col-md-4">
    <%= f.label :date_of_joining,'Date of joining' %>
    <div class="form control">
    <%= f.date_select(:date_of_joining, order: [:day, :month, :year],start_year: 2000) %>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    <%= f.label :work_phone %>
    <%= f.text_field :work_phone,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :education %>
    <%= f.text_area :education,class:"form-control" %>
    </div>
    <div class="col-md-4">
    <%= f.label :comments %>
    <%= f.text_area :comments,class:"form-control" %>
    </div>
    </div>
    <div class="row">
    <div class="col-md-2">
    <%= f.label :is_active,"Is Active" %>
    <%= f.radio_button(:is_active,true) %>
    </div>
    <div class="col-md-2">
    <%= f.label :is_active,"Is locked" %>
    <%= f.radio_button(:is_active,false) %>
    </div>
    <div class="col-md-4">
    <%= f.label :date_of_deactivation,'Date of deactivation' %>
    <%# text_field_tag :date_of_deactivation , "data-provide"=>'datepicker',class:"form-control" %>
    <div class="form control">
    <%= f.date_select :date_of_deactivation, order: [:day, :month, :year],start_year:1980 ,include_blank:true%>
    </div>
    </div>
    <div class="col-md-4">
    <%= f.label :reason_for_deactivation,'Reason for deactivation' %>
    <div class="form control">
    <%= f.select(:reason_for_deactivation, options_for_select([['No longer an employee with us'],['Absconding'],['Long Medical Live']]),class:"form-control") %>
    </div>
    </div>
    </div>
    </br>
    <div align="center">
    <%= f.submit class:"btn-primary"%>
    </div>
    <!--<div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>-->
<% end %>

app/views/users/show.html.erb
<h3>Welcome <%= @user.first_name %></h3>
<table class="table table-striped">
<tr>
  <td><strong>First name:</strong></td>
  <td><%= @user.first_name %></td>
</tr>
<tr>
  <td><strong>Middle name:</strong></td>
  <td><%= @user.middle_name %></td>
</tr>
<tr>
  <td><strong>Last name:</strong></td>
  <td><%= @user.last_name %></td>
</tr>
<tr>
  <td><strong>Email:</strong></td>
  <td><%= @user.email %></td>
</tr>
<tr>
  <td><strong>Login:</strong></td>
  <td><%= @user.login %></td>
</tr>
<tr>
  <td><strong>Employee id </strong></td>
  <td><%= @user.employee_id %></td>
</tr>
<tr>
<td><strong>Date of birth </strong></td>
  <td><%= @user.date_of_birth %></td>
</tr>
<tr>
<td><strong>Gender </strong></td>
  <td><%= @user.gender %></td>
</tr>
<tr>
<td><strong>Time_zone </strong></td>
  <td><%= @user.time_zone %></td>
</tr>
<tr>
<td><strong>Gender </strong></td>
  <td><%= @user.gender %></td>
</tr>
<tr>
<td><strong>Date of joining </strong></td>
  <td><%= @user.date_of_joining %></td>
</tr>
<tr>
<td><strong>Designation id </strong></td>
  <td><%= @user.designation_id %></td>
</tr>
<td><strong>Education </strong></td>
  <td><%= @user.education %></td>
<tr>
<td><strong>Work phone </strong></td>
  <td><%= @user.work_phone %></td>
</tr>
<tr>
<td><strong>Role </strong></td>
  <td><%= @user.role.name%></td>
</tr>
</table>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>